### ISSUE TITLE
Joystick Aufbau

### ISSUE THREAD

**Issue by SimH1993** [SimH1993/OTHR_AUTOSARSS18#2]
Bitte den Joystick auf einen Steckbreck so aufbauen, dass wir diesen nur noch an den Brick anschließen brauchen. Hier bitte auch die Dokumentation lesen somit wir wissen wie der Joystick genau funktioniert (Welche Spannung er wann zurück gibt).

**Comment by Milacus** [comment]
Von welcher Dokumentation hast du denn eigentlich gesprochen? Hardware haben wir so weit auf einem Breadboard aufgebaut und kurz mal in Betrieb genommen.

Könnten also mit der Implementierung für den Prototypen beginnen.

Problem dabei ist bloß noch, dass der Joystick evtl. für andere Kurse benötigt wird und daher immer wieder mal verschwinden könnte.
